version: "3"
services:
    frontend:
        build:
            context: .
            dockerfile: ./docker/frontend.dockerfile
        image: chatroom-frontend
        ports:
            - "9999:3000"
        restart: always